### PR TITLE
Port do_sqlite3 test to RSpec3

### PR DESCRIPTION
**Pull request by balasankarc**

### CODE REVIEW

**Comment by dbussink** [comment]
I would welcome a move to rspec3, but would prefer if it's done everywhere consistently and not just in one spec file.

**Comment by balasankarc** [comment]
You meant every do_* gems?

**Comment by dbussink** [comment]
@balasankarc Yes and also all spec files, this just seems to change one. All the gems are in this repository and I want to have a consistent style used for the whole repo and not a mix of different approaches.

**Comment by balasankarc** [comment]
> this just seems to change one

I used the gem transpec to do the porting. It caught only this file. I think rest all are RSpec3-happy. Anyway, I'll try to port other gems' tests also (I did this as part of maintaining the Debian package)

**Pull request closed without merging**
