### PR TITLE
Ruby 2.2 fix for do_mysql & do_postgres

### PR DESCRIPTION
**Pull request by dxg**
Should resolve datamapper/do#74

Based on [github.com/zk-ruby/zookeeper/pull/74/files](https://github.com/zk-ruby/zookeeper/pull/74/files)

### CODE REVIEW

**Comment by dxg** [comment]
Tests for postgres & mysql are green, however there seems to be a sqlite failure :-\
Not really sure why..

**Comment by dbussink** [comment]
It looks like there's some behavior difference somehow for 2.2 and Time objects. Would need to dig in a bit further to find out what it is. I hope to have some time next week so I can do a release with this fix and also include #76 in the new version.

**Comment by dbussink** [comment]
This change in itself seems good btw :+1:

**Comment by dbussink** [comment]
Looks like the failure in 2.2 might be due to https://byparker.com/blog/2014/ruby-2-2-0-time-parse-localtime-regression/

**Comment by dxg** [comment]
You were spot on. As in that blog post, adding `.localtime` fixed the problem.
I suspect it's related to sqlite ignoring timezones for the most part.
The mysql specs pass because they don't include the `'supporting sub second Time'` shared example as mysql up until very recently, [didn't support fractional seconds](http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html).
Postgres on the other hand defines the column as `timestamp with time zone` so everything works as expected.

**Comment by dbussink** [comment]
@dxg Thanks for the fix! 

The release process is kind of involved with all the prebuild JRuby and Windows gems and I don't think I can get to that in the next two weeks though since I'm travelling and won't have the machine with me where I have that all set up. 

Also I want to try if I can build for 2.1 on Windows to fix #72 so that probably means some more tinkering with that build environment.

**Comment by dbussink** [comment]
This has been released now, thanks again for the fix!

**Comment by danielb2** [comment]
I had to revert to 2.1.5 because its' not working on ruby 2.2.0 for me :/

```
2015-03-04T23:18:42.763950+00:00 app[web.1]: unicorn worker[0] -p 35920 -E production: symbol lookup
 error: /app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/do_postgres-0.10.9/do_pos
tgres/do_postgres.so: undefined symbol: rb_thread_select
```

**Comment by dxg** [comment]
The fixed for ruby 2.2 `do_postgres` is `0.10.15`. You're using `0.10.9`.

**Comment by danielb2** [comment]
thanks much

**Pull request merged**
